name = "skycms-contact-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Optional: set to a fixed hostname if you donâ€™t want to use the inbound host
[vars]
BACKEND_HOST_DNS_NAME = "edit.customwebarts.com"
ZONE_NAME = "customwebarts.com"
# ORIGIN_HOST_OVERRIDE = "www.customwebarts.com"

routes = [
  # adjust zone_name and host as needed
  { pattern = BACKEND_HOST_DNS_NAME + "/_api/contact/*", zone_name = ZONE_NAME }
  # { pattern = "customwebarts.com/_api/contact/*", zone_name = ZONE_NAME }
]